### ISSUE TITLE
@trendyol/cookie-helper is not in npmjs.org registry

### ISSUE THREAD

**Issue by ozanbatuhanceylan** [Trendyol/ty-cookie-helper#6]
#### Steps to reproduce 
1. run `npm i @trendyol/cookie-helper`

#### Current behaviour
npm fires a 404 error

#### Expected behaviour
Install package from npmjs.org registry

#### Relevant logs
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@trendyol%2fcookie-helper - Not found
npm ERR! 404 
npm ERR! 404  '@trendyol/cookie-helper@^1.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

If you publish the package i would like to try and may use the package in my projects.

**Comment by mehmetsefabalik** [comment]
hey, thank you for the issue, I will fix this ASAP

**Comment by mehmetsefabalik** [comment]
you can now install it @ozanbatuhanceylan , happy coding!

**Comment by ozanbatuhanceylan** [comment]
Are you sure that you publish the package into npmjs registry? Cause npm cannot find the package and fires the same error.

**Comment by mehmetsefabalik** [comment]
I had to change the naming, here is the link to the package: https://www.npmjs.com/package/@trendyol-js/cookie-helper

**Comment by ozanbatuhanceylan** [comment]
Thank you. It worked well now
